In [ ]:
l1=[1,"raju",30]
l2=[[10,20,30,40],[1,2,3,4]]
print(l1)
print(l2)
l1.append(8.5)
print(l1)
l1.insert(2,'cse')
print(l1)
print(l1.pop())
print(l1)
l1.remove('cse')
print(l1)
for i in l2:
  print(i)
for i in l1:
  print(l1)
print(l1[1])

[1, 'raju', 30]
[[10, 20, 30, 40], [1, 2, 3, 4]]
[1, 'raju', 30, 8.5]
[1, 'raju', 'cse', 30, 8.5]
8.5
[1, 'raju', 'cse', 30]
[1, 'raju', 30]
[10, 20, 30, 40]
[1, 2, 3, 4]
[1, 'raju', 30]
[1, 'raju', 30]
[1, 'raju', 30]
raju


In [ ]:
import numpy as np
a1=[10,20,30,40]
a2=[[1,2],[4,5]]
print(a1)
print(a2)
a=np.array(a1)
b=np.array(a2)
c=np.array([[10,20],[30,40]])
print(a)
print(b)
print(c)
print(b+c)
print(c-b)
print(5*c)
print(b*c)
print(np.matmul(c,b))
d=np.array([[1,-2,3],[-4,5,6]])
print(np.transpose(d))
print(np.linalg.inv(c))
print(d[1][1]*d[0][0])
print(np.eye(3))

[10, 20, 30, 40]
[[1, 2], [4, 5]]
[10 20 30 40]
[[1 2]
 [4 5]]
[[10 20]
 [30 40]]
[[11 22]
 [34 45]]
[[ 9 18]
 [26 35]]
[[ 50 100]
 [150 200]]
[[ 10  40]
 [120 200]]
[[ 90 120]
 [190 260]]
[[ 1 -4]
 [-2  5]
 [ 3  6]]
[[-0.2   0.1 ]
 [ 0.15 -0.05]]
5
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import pandas as pd
std_info=([1,"raju",30],[2,"ramu",28],[3,"somu",31],
          [1,"raju",30],[2,"ramu",28],[3,"somu",31])
std_info
df=pd.DataFrame(std_info,columns=["sid","sname","sage"])
df


sid sname  sage
0    1  raju    30
1    2  ramu    28
2    3  somu    31
3    1  raju    30
4    2  ramu    28
5    3  somu    31